services:
  postgres:
    image: postgres:latest
    container_name: "postgres_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finance_manager
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  application:
    build: .
    container_name: application
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/finance_manager
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      JWT_SECRET: SPRINGBOOTTRIEUHOANGKHANGDEPTRAITESTSECURITYCONSTANT12345678910
    depends_on:
      - postgres